language: generic
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      arch: ppc64le
      compiler: g++
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpq-dev
      env:
        - CXX=g++-9 BUILD=Release
      install:
        # Download and install recent cmake
        - |
          if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
            BOOST_URL="https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz"
            mkdir -p ${DEPS_DIR}/boost
            travis_retry wget --no-check-certificate --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/boost
            cd boost
            ./bootstrap.sh
            ./b2 -j12 install
            export PATH=${DEPS_DIR}/boost/stage:${PATH}
          fi
    - os: linux
      arch: amd64
      compiler: g++
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpq-dev
            - boost1.70
      env:
        - CXX=g++-9 BUILD=Release
  
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - make RunTests
     
