language: generic
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      arch: s390x
      compiler: g++
      sudo: true
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpq-dev
      env:
        - CXX=g++-9 BUILD=Release
      install:
        # Download and install recent boost
        - |
          if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
            echo "Systems Byte Order:"
            lscpu | grep "Byte Order"
            BOOST_URL="https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz"
            wget ${BOOST_URL}
            tar -xzf boost_1_72_0.tar.gz
            cd boost_1_72_0
            sudo cp -r boost /usr/local/include/
            #./bootstrap.sh
            #./b2 --without-atomic --without-chrono --without-container --without-context --without-contract --without-coroutine --without-date_time --without-exception --without-fiber --without-filesystem --without-graph --without-graph_parallel --without-headers --without-iostreams --without-locale --without-log --without-math --without-mpi --without-program_options --without-python --without-random --without-regex --without-serialization --without-stacktrace --without-system --without-test --without-thread --without-timer --without-type_erasure --without-wave install
            cd ..
            wget https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5.tar.gz
            tar -xzf cmake-3.16.5.tar.gz
            cd cmake-3.16.5
            ./bootstrap
            sudo make -j16 install
            cd ..
          fi
    - os: linux
      arch: amd64
      compiler: g++
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpq-dev
            - boost1.70
      env:
        - CXX=g++-9 BUILD=Release
  
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - make RunTests
     
