language: generic
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      arch: ppc64le
      compiler: g++
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpq-dev
            - boost1.64
      env:
        - CXX=g++-9 BUILD=Release
    - os: linux
      arch: amd64
      compiler: g++
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpq-dev
            - boost1.70
      env:
        - CXX=g++-9 BUILD=Release
  
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - make RunTests
     
