language: generic
os: linux
dist: xenial

branches:
  only:
    - master

matrix:
  arch:
    - amd64
    - ppc64le
  include:
    - compiler: g++
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpq-dev
            - libboost-all-dev
            - boost1.70
      env:
        - CXX=g++-9 BUILD=Release
 
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - make RunTests
     
